### PR TITLE
rename minor to minorTensr

### PR DESCRIPTION
**Pull request by lgarren**

### CODE REVIEW

**Comment by lgarren** [comment]
This is hopefully a test of a real change.  Patrick, does someone need to approve the PR before the next step happens?  I'm still a bit confused.  Right now all steps are pending.

Lynn

On 11/18/19 3:58 PM, Fermilab build bot account wrote:

A new Pull Request was created by @lgarren<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lgarren&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=5VBPbiwl_nuOSZJ9BfkLQPXYr6RRbSZ3z6sijnlwRqM&s=Bi-U_Mnirz4vycGvK9BA0DGIRKw11r_cxMpZP7kUvXw&e=> (Lynn Garren) for develop.

It involves the following packages:

lardata

@knoepfel<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_knoepfel&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=5VBPbiwl_nuOSZJ9BfkLQPXYr6RRbSZ3z6sijnlwRqM&s=oEmB-p3XOYwkqpNcg1EkbrD7asznpIreHbxyr-XbaAc&e=>, @lgarren<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lgarren&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=5VBPbiwl_nuOSZJ9BfkLQPXYr6RRbSZ3z6sijnlwRqM&s=Bi-U_Mnirz4vycGvK9BA0DGIRKw11r_cxMpZP7kUvXw&e=>, @gartung<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_gartung&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=5VBPbiwl_nuOSZJ9BfkLQPXYr6RRbSZ3z6sijnlwRqM&s=Wwca1wvKLtxr83AAc-fKjTTkPiUrH1_aiNzsVGa_qRg&e=>, @erica-snider<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_erica-2Dsnider&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=5VBPbiwl_nuOSZJ9BfkLQPXYr6RRbSZ3z6sijnlwRqM&s=12AvI1mz6z-eQdwVA4M25gOK1tQxrkaY1UZgKVuE1GI&e=>, @FNALbuild<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_FNALbuild&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=5VBPbiwl_nuOSZJ9BfkLQPXYr6RRbSZ3z6sijnlwRqM&s=WSSKeeWm7yJxFRvCXH9HVIDjOPpvH1ymgSJF9Uu6Zlo&e=>, @chissg<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_chissg&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=5VBPbiwl_nuOSZJ9BfkLQPXYr6RRbSZ3z6sijnlwRqM&s=rXrVlEtnzrOiis8F5A7B5m1dpP8oCL_oguzH2xWmoUA&e=> can you please review it and eventually sign? Thanks.
@gartung<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_gartung&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=5VBPbiwl_nuOSZJ9BfkLQPXYr6RRbSZ3z6sijnlwRqM&s=Wwca1wvKLtxr83AAc-fKjTTkPiUrH1_aiNzsVGa_qRg&e=> this is something you requested to watch as well.

cms-bot commands are listed here<https://urldefense.proofpoint.com/v2/url?u=http-3A__cms-2Dsw.github.io_cms-2Dbot-2Dcmssw-2Dcmds.html&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=5VBPbiwl_nuOSZJ9BfkLQPXYr6RRbSZ3z6sijnlwRqM&s=EdsZJGU9hrJPq9tJkA19JRUnssir4_aPpMZ9oTLM4RA&e=>

**Comment by gartung** [comment]
Yes. Start with please test

**Comment by lgarren** [comment]
please test

On 11/18/19 3:58 PM, Fermilab build bot account wrote:

A new Pull Request was created by @lgarren<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lgarren&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=5VBPbiwl_nuOSZJ9BfkLQPXYr6RRbSZ3z6sijnlwRqM&s=Bi-U_Mnirz4vycGvK9BA0DGIRKw11r_cxMpZP7kUvXw&e=> (Lynn Garren) for develop.

It involves the following packages:

lardata

@knoepfel<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_knoepfel&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=5VBPbiwl_nuOSZJ9BfkLQPXYr6RRbSZ3z6sijnlwRqM&s=oEmB-p3XOYwkqpNcg1EkbrD7asznpIreHbxyr-XbaAc&e=>, @lgarren<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lgarren&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=5VBPbiwl_nuOSZJ9BfkLQPXYr6RRbSZ3z6sijnlwRqM&s=Bi-U_Mnirz4vycGvK9BA0DGIRKw11r_cxMpZP7kUvXw&e=>, @gartung<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_gartung&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=5VBPbiwl_nuOSZJ9BfkLQPXYr6RRbSZ3z6sijnlwRqM&s=Wwca1wvKLtxr83AAc-fKjTTkPiUrH1_aiNzsVGa_qRg&e=>, @erica-snider<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_erica-2Dsnider&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=5VBPbiwl_nuOSZJ9BfkLQPXYr6RRbSZ3z6sijnlwRqM&s=12AvI1mz6z-eQdwVA4M25gOK1tQxrkaY1UZgKVuE1GI&e=>, @FNALbuild<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_FNALbuild&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=5VBPbiwl_nuOSZJ9BfkLQPXYr6RRbSZ3z6sijnlwRqM&s=WSSKeeWm7yJxFRvCXH9HVIDjOPpvH1ymgSJF9Uu6Zlo&e=>, @chissg<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_chissg&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=5VBPbiwl_nuOSZJ9BfkLQPXYr6RRbSZ3z6sijnlwRqM&s=rXrVlEtnzrOiis8F5A7B5m1dpP8oCL_oguzH2xWmoUA&e=> can you please review it and eventually sign? Thanks.
@gartung<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_gartung&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=5VBPbiwl_nuOSZJ9BfkLQPXYr6RRbSZ3z6sijnlwRqM&s=Wwca1wvKLtxr83AAc-fKjTTkPiUrH1_aiNzsVGa_qRg&e=> this is something you requested to watch as well.

cms-bot commands are listed here<https://urldefense.proofpoint.com/v2/url?u=http-3A__cms-2Dsw.github.io_cms-2Dbot-2Dcmssw-2Dcmds.html&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=5VBPbiwl_nuOSZJ9BfkLQPXYr6RRbSZ3z6sijnlwRqM&s=EdsZJGU9hrJPq9tJkA19JRUnssir4_aPpMZ9oTLM4RA&e=>

**Comment by gartung** [comment]
The correct command is
trigger tests

**Comment by gartung** [comment]
Correct the correct command is
trigger build

**Comment by gartung** [comment]
command trigger build must be on the first line

**Comment by gartung** [comment]
please trigger build

**Comment by knoepfel** [comment]
Two small things, but nothing that should prevent a merge:

- Rename `minorTensr` to `minorTensor`; otherwise it looks like a misspelling.
- I'd add a comment where `minorTensor` is defined explaining why choosing a name like `minor` is problematic.

**Comment by lgarren** [comment]
Well, the spelling was deliberate on my part, but I'll change it.

On 11/18/19 9:14 PM, Kyle Knoepfel wrote:

Two small things, but nothing that should prevent a merge:

  *   Rename minorTensr to minorTensor; otherwise it looks like a misspelling.
  *   I'd add a comment where minorTensor is defined explaining why choosing a name like minor is problematic.

**Comment by lgarren** [comment]
trigger build

On 11/18/19 9:33 PM, Fermilab build bot account wrote:

Pull request #1<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_LArSoft_lardata_pull_1&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=ICDUdvWBn9twGAONNt6ToVaywsAXDq9wWKO3nx-aRH0&s=Vpgrp86ZamH5PSiCJTC2jOnUCw3KsE2djjLGI_Z7I3Q&e=> was updated. @knoepfel<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_knoepfel&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=ICDUdvWBn9twGAONNt6ToVaywsAXDq9wWKO3nx-aRH0&s=hHbCwLTrV8P_Og4ZbowoJLplOmvq9Zlwe4hiCgyb6U4&e=>, @lgarren<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lgarren&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=ICDUdvWBn9twGAONNt6ToVaywsAXDq9wWKO3nx-aRH0&s=ycfyeO-wr-HOGKKe8Hw9UXZzr-5QyTpYu2d3XkJ_Eqo&e=>, @gartung<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_gartung&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=ICDUdvWBn9twGAONNt6ToVaywsAXDq9wWKO3nx-aRH0&s=kZCh5dwzO9lF2-eo3DEWPMm6gSF1xMF992OLhe98A0A&e=>, @erica-snider<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_erica-2Dsnider&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=ICDUdvWBn9twGAONNt6ToVaywsAXDq9wWKO3nx-aRH0&s=YrWg9-GDmV8eox6SGw5LJl9zMdNioCur7wub0I5kf4M&e=>, @FNALbuild<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_FNALbuild&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=ICDUdvWBn9twGAONNt6ToVaywsAXDq9wWKO3nx-aRH0&s=i18FWQg33us8ejuCMNEDkWm04H9nZURqot7_HR3fPNU&e=>, @chissg<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_chissg&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=ICDUdvWBn9twGAONNt6ToVaywsAXDq9wWKO3nx-aRH0&s=HBJxdxUzKWBbud2pvqYK8cpnvw5fTVX0b9RARoP-jM4&e=> can you please check and sign again.

**Comment by knoepfel** [comment]
approve

**Comment by lgarren** [comment]
code-checks

**Pull request merged**
