### PR TITLE
counterpart of SignalShaping for multithreaded operation

### PR DESCRIPTION
**Pull request by mhlswang**
This plays the same role as SignalShaping but allows thread-safe/multithreaded operation of 1d fft-deconvolution of raw waveforms.  Meant to accompany LArFFTW/LArFFTWPlan.

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

**Comment by knoepfel** [comment]
trigger build

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
