### PR TITLE
Allow range-for loop on associated_groups_with_left() output

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
Including a C++17-aware unit test.

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
Had to rerun the dune CI.  Here are the results.
https://dbweb8.fnal.gov:8443/LarCI/app/ns:DUNE/view_builds/index?offset=0&builds=dune_ci/10764&builds=

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
